printf "# Generated by set-dns-servers.sh from Cyphred's arch install scripts\nnameserver\t8.8.8.8\nnameserver\t8.8.4.4\n" > /etc/resolv.conf || exit 1

# Set the file attribute to immutable so that it can't be overwritten
chattr +i /etc/resolv.conf
